# Generated by Django 4.2.16 on 2024-09-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_lat_customuser_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='long',
            new_name='lon',
        ),
    ]
