# Generated by Django 4.2.16 on 2024-09-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
