# Generated by Django 5.1.1 on 2024-10-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customuser_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(default='Unassigned', max_length=30),
        ),
    ]
