# Generated by Django 5.1.1 on 2024-10-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_customuser_profile_picture'),
        ('datahub', '0006_rename_created_at_ticket_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datahub.thana'),
        ),
    ]
