# Generated by Django 5.1.1 on 2024-10-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_customuser_thana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='thana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
