# Generated by Django 5.1.1 on 2024-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
