# Generated by Django 4.2.16 on 2024-09-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_otp_expiration_customuser_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
