# Generated by Django 4.2.16 on 2024-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_long_customuser_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
