# Generated by Django 5.1.1 on 2024-09-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_lat_alter_customuser_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
