# Generated by Django 5.1.1 on 2024-09-25 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_lat', models.CharField(max_length=255)),
                ('user_lon', models.CharField(max_length=255)),
                ('police_lat', models.CharField(blank=True, max_length=255, null=True)),
                ('police_lon', models.CharField(blank=True, max_length=255, null=True)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
