# Generated by Django 4.2.16 on 2024-09-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_radio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='thana',
        ),
        migrations.AddField(
            model_name='contact',
            name='thana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='datahub.primarythana'),
        ),
    ]
