# Generated by Django 5.1.1 on 2024-10-18 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0006_rename_created_at_ticket_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='documents',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_documents/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='datahub.ticket')),
            ],
        ),
    ]
