# Generated by Django 4.2.16 on 2024-09-20 21:00

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('name_bn', models.CharField(max_length=555)),
                ('file', models.FileField(upload_to='radios/', validators=[datahub.models.validate_audio_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
