# Generated by Django 4.2.16 on 2024-09-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0003_remove_contact_thana_contact_thana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='datahub.primarythana'),
        ),
    ]
