# Generated by Django 5.1.1 on 2024-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0004_alter_contact_thana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_bn',
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='#', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(default='#', upload_to='news_thumbnails/'),
        ),
    ]
