# Generated by Django 5.1.1 on 2024-10-16 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0005_remove_news_description_remove_news_description_bn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='message_documents/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='message',
            field=models.TextField(default='#'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
